name: Build github-sync Image

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: github-sync/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
